import sila as s
import matplotlib.pyplot as plt
s1=s.sila()
def F1(x,v,t):
    return(4)
s1.set_initial_conditions(10,5,2,F1)
s1.a_t_graf()
plt.show()
s1.reset()
s1.set_initial_conditions(10,5,2,F1)
s1.v_t_graf()
plt.show()
s1.reset()
s1.set_initial_conditions(10,5,2,F1)
s1.x_t_graf()
plt.show()
s1.reset()
def F2(x,v,t):
    return(-4*x)
s1.set_initial_conditions(10,5,2,F2)
s1.a_t_graf()
plt.show()
s1.reset()
s1.set_initial_conditions(10,5,2,F2)
s1.v_t_graf()
plt.show()
s1.reset()
s1.set_initial_conditions(10,5,2,F2)
s1.x_t_graf()
plt.show()
s1.reset()